version: '3.8'

services:
  tellmeapp:
    build: .
    container_name: tellmeapp
    volumes:
      # Монтируем текущую директорию для разработки
      - .:/app
    environment:
      # Настройки для отображения GUI
      - DISPLAY=${DISPLAY}
      # Настройки Kivy
      - KIVY_WINDOW=sdl2
    network_mode: host
    stdin_open: true
    tty: true
